version: "3.3"
services:
  hadoop_master:
    build: ./Dockerfile
    image: hadoop
    networks:
      hadoop:
    ports:
      - "8088:8088"
      - "50070:50070"
  hadoop_slave:
    build:
      context: .
      dockerfile: ./Dockerfile_slave
    image: hadoop_slave
    networks:
      hadoop:
networks:
  hadoop:
