version: "3.3"
services:
  hadoop_master:
    build: .
    image: hadoop_master
    networks:
      hadoop:
    ports:
      - "8088:8088"
      - "50070:50070"
  hadoop_slave:
    build:
      context: .
      args:
        NODE_TYPE: slave
    image: hadoop_slave
    networks:
      hadoop:
networks:
  hadoop:
